// automatically generated by the FlatBuffers compiler, do not modify

// @generated

extern crate flatbuffers;

#[allow(unused_imports, dead_code)]
pub mod account_info {

    use core::cmp::Ordering;
    use core::mem;

    extern crate flatbuffers;
    use self::flatbuffers::{EndianScalar, Follow};

    pub enum AccountInfoOffset {}
    #[derive(Copy, Clone, PartialEq)]

    pub struct AccountInfo<'a> {
        pub _tab: flatbuffers::Table<'a>,
    }

    impl<'a> flatbuffers::Follow<'a> for AccountInfo<'a> {
        type Inner = AccountInfo<'a>;
        #[inline]
        unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
            Self {
                _tab: flatbuffers::Table::new(buf, loc),
            }
        }
    }

    impl<'a> AccountInfo<'a> {
        pub const VT_PUBKEY: flatbuffers::VOffsetT = 4;
        pub const VT_OWNER: flatbuffers::VOffsetT = 6;
        pub const VT_SLOT: flatbuffers::VOffsetT = 8;
        pub const VT_ACCOUNT_DATA: flatbuffers::VOffsetT = 10;

        #[inline]
        pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
            AccountInfo { _tab: table }
        }
        #[allow(unused_mut)]
        pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr>(
            _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr>,
            args: &'args AccountInfoArgs<'args>,
        ) -> flatbuffers::WIPOffset<AccountInfo<'bldr>> {
            let mut builder = AccountInfoBuilder::new(_fbb);
            builder.add_slot(args.slot);
            if let Some(x) = args.account_data {
                builder.add_account_data(x);
            }
            if let Some(x) = args.owner {
                builder.add_owner(x);
            }
            if let Some(x) = args.pubkey {
                builder.add_pubkey(x);
            }
            builder.finish()
        }

        #[inline]
        pub fn pubkey(&self) -> Option<&'a str> {
            // Safety:
            // Created from valid Table for this object
            // which contains a valid value in this slot
            unsafe {
                self._tab
                    .get::<flatbuffers::ForwardsUOffset<&str>>(AccountInfo::VT_PUBKEY, None)
            }
        }
        #[inline]
        pub fn owner(&self) -> Option<&'a str> {
            // Safety:
            // Created from valid Table for this object
            // which contains a valid value in this slot
            unsafe {
                self._tab
                    .get::<flatbuffers::ForwardsUOffset<&str>>(AccountInfo::VT_OWNER, None)
            }
        }
        #[inline]
        pub fn slot(&self) -> u64 {
            // Safety:
            // Created from valid Table for this object
            // which contains a valid value in this slot
            unsafe { self._tab.get::<u64>(AccountInfo::VT_SLOT, Some(0)).unwrap() }
        }
        #[inline]
        pub fn account_data(&self) -> Option<flatbuffers::Vector<'a, u8>> {
            // Safety:
            // Created from valid Table for this object
            // which contains a valid value in this slot
            unsafe {
                self._tab
                    .get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, u8>>>(
                        AccountInfo::VT_ACCOUNT_DATA,
                        None,
                    )
            }
        }
    }

    impl flatbuffers::Verifiable for AccountInfo<'_> {
        #[inline]
        fn run_verifier(
            v: &mut flatbuffers::Verifier,
            pos: usize,
        ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
            use self::flatbuffers::Verifiable;
            v.visit_table(pos)?
                .visit_field::<flatbuffers::ForwardsUOffset<&str>>(
                    "pubkey",
                    Self::VT_PUBKEY,
                    false,
                )?
                .visit_field::<flatbuffers::ForwardsUOffset<&str>>("owner", Self::VT_OWNER, false)?
                .visit_field::<u64>("slot", Self::VT_SLOT, false)?
                .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, u8>>>(
                    "account_data",
                    Self::VT_ACCOUNT_DATA,
                    false,
                )?
                .finish();
            Ok(())
        }
    }
    pub struct AccountInfoArgs<'a> {
        pub pubkey: Option<flatbuffers::WIPOffset<&'a str>>,
        pub owner: Option<flatbuffers::WIPOffset<&'a str>>,
        pub slot: u64,
        pub account_data: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, u8>>>,
    }
    impl<'a> Default for AccountInfoArgs<'a> {
        #[inline]
        fn default() -> Self {
            AccountInfoArgs {
                pubkey: None,
                owner: None,
                slot: 0,
                account_data: None,
            }
        }
    }

    pub struct AccountInfoBuilder<'a: 'b, 'b> {
        fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a>,
        start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
    }
    impl<'a: 'b, 'b> AccountInfoBuilder<'a, 'b> {
        #[inline]
        pub fn add_pubkey(&mut self, pubkey: flatbuffers::WIPOffset<&'b str>) {
            self.fbb_
                .push_slot_always::<flatbuffers::WIPOffset<_>>(AccountInfo::VT_PUBKEY, pubkey);
        }
        #[inline]
        pub fn add_owner(&mut self, owner: flatbuffers::WIPOffset<&'b str>) {
            self.fbb_
                .push_slot_always::<flatbuffers::WIPOffset<_>>(AccountInfo::VT_OWNER, owner);
        }
        #[inline]
        pub fn add_slot(&mut self, slot: u64) {
            self.fbb_.push_slot::<u64>(AccountInfo::VT_SLOT, slot, 0);
        }
        #[inline]
        pub fn add_account_data(
            &mut self,
            account_data: flatbuffers::WIPOffset<flatbuffers::Vector<'b, u8>>,
        ) {
            self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(
                AccountInfo::VT_ACCOUNT_DATA,
                account_data,
            );
        }
        #[inline]
        pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>) -> AccountInfoBuilder<'a, 'b> {
            let start = _fbb.start_table();
            AccountInfoBuilder {
                fbb_: _fbb,
                start_: start,
            }
        }
        #[inline]
        pub fn finish(self) -> flatbuffers::WIPOffset<AccountInfo<'a>> {
            let o = self.fbb_.end_table(self.start_);
            flatbuffers::WIPOffset::new(o.value())
        }
    }

    impl core::fmt::Debug for AccountInfo<'_> {
        fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
            let mut ds = f.debug_struct("AccountInfo");
            ds.field("pubkey", &self.pubkey());
            ds.field("owner", &self.owner());
            ds.field("slot", &self.slot());
            ds.field("account_data", &self.account_data());
            ds.finish()
        }
    }
    #[inline]
    /// Verifies that a buffer of bytes contains a `AccountInfo`
    /// and returns it.
    /// Note that verification is still experimental and may not
    /// catch every error, or be maximally performant. For the
    /// previous, unchecked, behavior use
    /// `root_as_account_info_unchecked`.
    pub fn root_as_account_info(buf: &[u8]) -> Result<AccountInfo, flatbuffers::InvalidFlatbuffer> {
        flatbuffers::root::<AccountInfo>(buf)
    }
    #[inline]
    /// Verifies that a buffer of bytes contains a size prefixed
    /// `AccountInfo` and returns it.
    /// Note that verification is still experimental and may not
    /// catch every error, or be maximally performant. For the
    /// previous, unchecked, behavior use
    /// `size_prefixed_root_as_account_info_unchecked`.
    pub fn size_prefixed_root_as_account_info(
        buf: &[u8],
    ) -> Result<AccountInfo, flatbuffers::InvalidFlatbuffer> {
        flatbuffers::size_prefixed_root::<AccountInfo>(buf)
    }
    #[inline]
    /// Verifies, with the given options, that a buffer of bytes
    /// contains a `AccountInfo` and returns it.
    /// Note that verification is still experimental and may not
    /// catch every error, or be maximally performant. For the
    /// previous, unchecked, behavior use
    /// `root_as_account_info_unchecked`.
    pub fn root_as_account_info_with_opts<'b, 'o>(
        opts: &'o flatbuffers::VerifierOptions,
        buf: &'b [u8],
    ) -> Result<AccountInfo<'b>, flatbuffers::InvalidFlatbuffer> {
        flatbuffers::root_with_opts::<AccountInfo<'b>>(opts, buf)
    }
    #[inline]
    /// Verifies, with the given verifier options, that a buffer of
    /// bytes contains a size prefixed `AccountInfo` and returns
    /// it. Note that verification is still experimental and may not
    /// catch every error, or be maximally performant. For the
    /// previous, unchecked, behavior use
    /// `root_as_account_info_unchecked`.
    pub fn size_prefixed_root_as_account_info_with_opts<'b, 'o>(
        opts: &'o flatbuffers::VerifierOptions,
        buf: &'b [u8],
    ) -> Result<AccountInfo<'b>, flatbuffers::InvalidFlatbuffer> {
        flatbuffers::size_prefixed_root_with_opts::<AccountInfo<'b>>(opts, buf)
    }
    #[inline]
    /// Assumes, without verification, that a buffer of bytes contains a AccountInfo and returns it.
    /// # Safety
    /// Callers must trust the given bytes do indeed contain a valid `AccountInfo`.
    pub unsafe fn root_as_account_info_unchecked(buf: &[u8]) -> AccountInfo {
        flatbuffers::root_unchecked::<AccountInfo>(buf)
    }
    #[inline]
    /// Assumes, without verification, that a buffer of bytes contains a size prefixed AccountInfo and returns it.
    /// # Safety
    /// Callers must trust the given bytes do indeed contain a valid size prefixed `AccountInfo`.
    pub unsafe fn size_prefixed_root_as_account_info_unchecked(buf: &[u8]) -> AccountInfo {
        flatbuffers::size_prefixed_root_unchecked::<AccountInfo>(buf)
    }
    #[inline]
    pub fn finish_account_info_buffer<'a, 'b>(
        fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>,
        root: flatbuffers::WIPOffset<AccountInfo<'a>>,
    ) {
        fbb.finish(root, None);
    }

    #[inline]
    pub fn finish_size_prefixed_account_info_buffer<'a, 'b>(
        fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>,
        root: flatbuffers::WIPOffset<AccountInfo<'a>>,
    ) {
        fbb.finish_size_prefixed(root, None);
    }
} // pub mod AccountInfo
