// automatically generated by the FlatBuffers compiler, do not modify

// @generated

extern crate flatbuffers;

#[allow(unused_imports, dead_code)]
pub mod metadata_off_chain {

    use core::cmp::Ordering;
    use core::mem;

    extern crate flatbuffers;
    use self::flatbuffers::{EndianScalar, Follow};

    pub enum MetadataOffChainOffset {}
    #[derive(Copy, Clone, PartialEq)]

    pub struct MetadataOffChain<'a> {
        pub _tab: flatbuffers::Table<'a>,
    }

    impl<'a> flatbuffers::Follow<'a> for MetadataOffChain<'a> {
        type Inner = MetadataOffChain<'a>;
        #[inline]
        fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
            Self {
                _tab: flatbuffers::Table { buf, loc },
            }
        }
    }

    impl<'a> MetadataOffChain<'a> {
        pub const VT_PUBKEY: flatbuffers::VOffsetT = 4;
        pub const VT_URI: flatbuffers::VOffsetT = 6;
        pub const VT_SLOT: flatbuffers::VOffsetT = 8;
        pub const VT_IS_STARTUP: flatbuffers::VOffsetT = 10;

        #[inline]
        pub fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
            MetadataOffChain { _tab: table }
        }
        #[allow(unused_mut)]
        pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr>(
            _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr>,
            args: &'args MetadataOffChainArgs<'args>,
        ) -> flatbuffers::WIPOffset<MetadataOffChain<'bldr>> {
            let mut builder = MetadataOffChainBuilder::new(_fbb);
            builder.add_slot(args.slot);
            if let Some(x) = args.uri {
                builder.add_uri(x);
            }
            if let Some(x) = args.pubkey {
                builder.add_pubkey(x);
            }
            builder.add_is_startup(args.is_startup);
            builder.finish()
        }

        #[inline]
        pub fn pubkey(&self) -> Option<&'a str> {
            self._tab
                .get::<flatbuffers::ForwardsUOffset<&str>>(MetadataOffChain::VT_PUBKEY, None)
        }
        #[inline]
        pub fn uri(&self) -> Option<&'a str> {
            self._tab
                .get::<flatbuffers::ForwardsUOffset<&str>>(MetadataOffChain::VT_URI, None)
        }
        #[inline]
        pub fn slot(&self) -> u64 {
            self._tab
                .get::<u64>(MetadataOffChain::VT_SLOT, Some(0))
                .unwrap()
        }
        #[inline]
        pub fn is_startup(&self) -> bool {
            self._tab
                .get::<bool>(MetadataOffChain::VT_IS_STARTUP, Some(false))
                .unwrap()
        }
    }

    impl flatbuffers::Verifiable for MetadataOffChain<'_> {
        #[inline]
        fn run_verifier(
            v: &mut flatbuffers::Verifier,
            pos: usize,
        ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
            use self::flatbuffers::Verifiable;
            v.visit_table(pos)?
                .visit_field::<flatbuffers::ForwardsUOffset<&str>>(
                    "pubkey",
                    Self::VT_PUBKEY,
                    false,
                )?
                .visit_field::<flatbuffers::ForwardsUOffset<&str>>("uri", Self::VT_URI, false)?
                .visit_field::<u64>("slot", Self::VT_SLOT, false)?
                .visit_field::<bool>("is_startup", Self::VT_IS_STARTUP, false)?
                .finish();
            Ok(())
        }
    }
    pub struct MetadataOffChainArgs<'a> {
        pub pubkey: Option<flatbuffers::WIPOffset<&'a str>>,
        pub uri: Option<flatbuffers::WIPOffset<&'a str>>,
        pub slot: u64,
        pub is_startup: bool,
    }
    impl<'a> Default for MetadataOffChainArgs<'a> {
        #[inline]
        fn default() -> Self {
            MetadataOffChainArgs {
                pubkey: None,
                uri: None,
                slot: 0,
                is_startup: false,
            }
        }
    }

    pub struct MetadataOffChainBuilder<'a: 'b, 'b> {
        fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a>,
        start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
    }
    impl<'a: 'b, 'b> MetadataOffChainBuilder<'a, 'b> {
        #[inline]
        pub fn add_pubkey(&mut self, pubkey: flatbuffers::WIPOffset<&'b str>) {
            self.fbb_
                .push_slot_always::<flatbuffers::WIPOffset<_>>(MetadataOffChain::VT_PUBKEY, pubkey);
        }
        #[inline]
        pub fn add_uri(&mut self, uri: flatbuffers::WIPOffset<&'b str>) {
            self.fbb_
                .push_slot_always::<flatbuffers::WIPOffset<_>>(MetadataOffChain::VT_URI, uri);
        }
        #[inline]
        pub fn add_slot(&mut self, slot: u64) {
            self.fbb_
                .push_slot::<u64>(MetadataOffChain::VT_SLOT, slot, 0);
        }
        #[inline]
        pub fn add_is_startup(&mut self, is_startup: bool) {
            self.fbb_
                .push_slot::<bool>(MetadataOffChain::VT_IS_STARTUP, is_startup, false);
        }
        #[inline]
        pub fn new(
            _fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>,
        ) -> MetadataOffChainBuilder<'a, 'b> {
            let start = _fbb.start_table();
            MetadataOffChainBuilder {
                fbb_: _fbb,
                start_: start,
            }
        }
        #[inline]
        pub fn finish(self) -> flatbuffers::WIPOffset<MetadataOffChain<'a>> {
            let o = self.fbb_.end_table(self.start_);
            flatbuffers::WIPOffset::new(o.value())
        }
    }

    impl core::fmt::Debug for MetadataOffChain<'_> {
        fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
            let mut ds = f.debug_struct("MetadataOffChain");
            ds.field("pubkey", &self.pubkey());
            ds.field("uri", &self.uri());
            ds.field("slot", &self.slot());
            ds.field("is_startup", &self.is_startup());
            ds.finish()
        }
    }
    #[inline]
    #[deprecated(since = "2.0.0", note = "Deprecated in favor of `root_as...` methods.")]
    pub fn get_root_as_metadata_off_chain<'a>(buf: &'a [u8]) -> MetadataOffChain<'a> {
        unsafe { flatbuffers::root_unchecked::<MetadataOffChain<'a>>(buf) }
    }

    #[inline]
    #[deprecated(since = "2.0.0", note = "Deprecated in favor of `root_as...` methods.")]
    pub fn get_size_prefixed_root_as_metadata_off_chain<'a>(buf: &'a [u8]) -> MetadataOffChain<'a> {
        unsafe { flatbuffers::size_prefixed_root_unchecked::<MetadataOffChain<'a>>(buf) }
    }

    #[inline]
    /// Verifies that a buffer of bytes contains a `MetadataOffChain`
    /// and returns it.
    /// Note that verification is still experimental and may not
    /// catch every error, or be maximally performant. For the
    /// previous, unchecked, behavior use
    /// `root_as_metadata_off_chain_unchecked`.
    pub fn root_as_metadata_off_chain(
        buf: &[u8],
    ) -> Result<MetadataOffChain, flatbuffers::InvalidFlatbuffer> {
        flatbuffers::root::<MetadataOffChain>(buf)
    }
    #[inline]
    /// Verifies that a buffer of bytes contains a size prefixed
    /// `MetadataOffChain` and returns it.
    /// Note that verification is still experimental and may not
    /// catch every error, or be maximally performant. For the
    /// previous, unchecked, behavior use
    /// `size_prefixed_root_as_metadata_off_chain_unchecked`.
    pub fn size_prefixed_root_as_metadata_off_chain(
        buf: &[u8],
    ) -> Result<MetadataOffChain, flatbuffers::InvalidFlatbuffer> {
        flatbuffers::size_prefixed_root::<MetadataOffChain>(buf)
    }
    #[inline]
    /// Verifies, with the given options, that a buffer of bytes
    /// contains a `MetadataOffChain` and returns it.
    /// Note that verification is still experimental and may not
    /// catch every error, or be maximally performant. For the
    /// previous, unchecked, behavior use
    /// `root_as_metadata_off_chain_unchecked`.
    pub fn root_as_metadata_off_chain_with_opts<'b, 'o>(
        opts: &'o flatbuffers::VerifierOptions,
        buf: &'b [u8],
    ) -> Result<MetadataOffChain<'b>, flatbuffers::InvalidFlatbuffer> {
        flatbuffers::root_with_opts::<MetadataOffChain<'b>>(opts, buf)
    }
    #[inline]
    /// Verifies, with the given verifier options, that a buffer of
    /// bytes contains a size prefixed `MetadataOffChain` and returns
    /// it. Note that verification is still experimental and may not
    /// catch every error, or be maximally performant. For the
    /// previous, unchecked, behavior use
    /// `root_as_metadata_off_chain_unchecked`.
    pub fn size_prefixed_root_as_metadata_off_chain_with_opts<'b, 'o>(
        opts: &'o flatbuffers::VerifierOptions,
        buf: &'b [u8],
    ) -> Result<MetadataOffChain<'b>, flatbuffers::InvalidFlatbuffer> {
        flatbuffers::size_prefixed_root_with_opts::<MetadataOffChain<'b>>(opts, buf)
    }
    #[inline]
    /// Assumes, without verification, that a buffer of bytes contains a MetadataOffChain and returns it.
    /// # Safety
    /// Callers must trust the given bytes do indeed contain a valid `MetadataOffChain`.
    pub unsafe fn root_as_metadata_off_chain_unchecked(buf: &[u8]) -> MetadataOffChain {
        flatbuffers::root_unchecked::<MetadataOffChain>(buf)
    }
    #[inline]
    /// Assumes, without verification, that a buffer of bytes contains a size prefixed MetadataOffChain and returns it.
    /// # Safety
    /// Callers must trust the given bytes do indeed contain a valid size prefixed `MetadataOffChain`.
    pub unsafe fn size_prefixed_root_as_metadata_off_chain_unchecked(
        buf: &[u8],
    ) -> MetadataOffChain {
        flatbuffers::size_prefixed_root_unchecked::<MetadataOffChain>(buf)
    }
    #[inline]
    pub fn finish_metadata_off_chain_buffer<'a, 'b>(
        fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>,
        root: flatbuffers::WIPOffset<MetadataOffChain<'a>>,
    ) {
        fbb.finish(root, None);
    }

    #[inline]
    pub fn finish_size_prefixed_metadata_off_chain_buffer<'a, 'b>(
        fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>,
        root: flatbuffers::WIPOffset<MetadataOffChain<'a>>,
    ) {
        fbb.finish_size_prefixed(root, None);
    }
} // pub mod MetadataOffChain
